### ISSUE TITLE
Various todo notes

### ISSUE THREAD

**Issue by jaekwon** [cosmos/cosmos#33]
- [ ] write about non-validator nodes, importance
- [ ] write about forks, slashing, effect on shards, insurance, etc
- [ ] write relationship between hub validators and shard validators
- [ ] economic estimates (?)
- [ ] should source shards use set rates or tranches (???)
- [ ] maybe change the inflation schedule to be exponential
- [ ] document procedure for crowdfund referrals.
- [ ] TODO
