### ISSUE TITLE
Be more specific about expectations and roadmap

### ISSUE THREAD

**Issue by jaekwon** [cosmos/cosmos#6]
- [ ] Include some text on top that shows the version, and how the whitepaper is expected to change much over the coming weeks, so the user checks the whitepaper for updates, e.g. weekly
- [ ] Include more detail in the roadmap, e.g. about what code needs to be written still
- [ ] Link to existing code where it exists.  Governmint is too bit immature to link, imo.
